### ISSUE TITLE
getNumberType always return undefined for Indonesia Phone Number

### ISSUE THREAD

**Issue by andangrd** [halt-hammerzeit/libphonenumber-js#61]
Hi,
I try to check whether my input is an Indonesia Phone Number or not by using getNumberType function, but i always get "undefined" although I input my correct phone number, 
Any idea or suggestion is really appreciated.

```javascript
const numberType = getNumberType(value, 'ID');
  if( numberType !== 'MOBILE'){
    return errorMessage;
  }
```

**Comment by halt-hammerzeit** [comment]
`getNumberType` always returns phone number type with the full metadata for a county.
With the default metadata use `parse()` instead.

**Comment by andangrd** [comment]
I use another option to solve it.
```javascript
  const formatter = new asYouType('ID');
  const input = formatter.input(value);
  const valid =  formatter.valid;
  if(!valid){
    return errorMessage;
  }
```

**Comment by halt-hammerzeit** [comment]
That works too.
It's the same as `parse(number, 'ID')`

**Comment by halt-hammerzeit** [comment]
Actually, there's a dedicated function for validating phone numbers: `isValidNumber(value, 'ID')`

**Comment by andangrd** [comment]
i got different result between isValidNumber and my previous solution for input = 1234567890.

when using isValidNumber, it returns true. Actually it should be false, right?
but I get the correct return when using my code above, it returns "false".

**Comment by halt-hammerzeit** [comment]
Provide the exact code

**Comment by andangrd** [comment]
check this one,

```javascript
const validate = (value) => {
  const isValidFn = isValidNumber(value, 'ID'); //it will return true

  const formatter = new asYouType('ID');
  formatter.input(value);
  const valid = formatter.valid; //it will return false

  return undefined;
}
```

**Comment by andangrd** [comment]
my previous solution is worked to validate all Indonesia phone number,
but how if i want to validate and make sure the input value is a mobile number.
i have tried to use 
```javascript
getNumberType('087717199324', 'ID') === 'MOBILE'
```
it always returns undefined,. that's a correct Indonesia number

**Comment by halt-hammerzeit** [comment]
I already explained that `getNumberType` only works for full metadata which is not the default one

**Comment by halt-hammerzeit** [comment]
I looked into the code you provided and turns out that "as you type" formatter was giving false negatives for `.valid` property, i.e. when it said `.valid === false` it just meant that it didn't find a phone number format for the phone number and didn't neccessary mean that the `value` is invalid (because for some countries there might be no phone number format but the phone number might still be valid - those are rare cases but they exist).
Therefore I released `0.4.x` version where I removed the `.valid` property completely.
As I said before, for more precise phone number validation use "full metadata" for desired countries.

**Comment by andangrd** [comment]
I tried to use your suggestion 
> It's the same as parse(value, 'ID')
but when I debug it, I get object value below: 

{ country: 'ID', phone: '85867899XXX' }

could you please give me example to get the numberType?
as I said, I want to check whether my input value is a valid Indonesia Mobile Number number or not.
Thank you,

**Comment by halt-hammerzeit** [comment]
First compile custom metadata for `ID` with the `--extended` flag.
Next use either `getNumberType()` or `isValidNumber()`.
And that should be working.

**Comment by andangrd** [comment]
i have run the script to compile custom metadata 
```
"libphonenumber-metadata": "libphonenumber-generate-metadata metadata.min.json --countries ID --extended"
```
then import and add custom function : 

```javascript
import { getNumberType } from 'libphonenumber-js';
import metadata from '../../metadata.min.json';

export const getNumberTypeCustom = (...args) => getNumberType(...args, metadata);

export const validate = errorKey => (value) => {
  if (isEmpty(value)) return undefined;

  const numberType = getNumberTypeCustom(value, 'ID');
  console.log(numberType)
  if (numberType !== 'MOBILE') {
    return errorMessage;
  }
  return undefined;
};
```

numberType still return undefined for a valid mobile phone number

**Comment by halt-hammerzeit** [comment]
https://github.com/halt-hammerzeit/libphonenumber-js#customizing-metadata

You're using the wrong exports.
The correct exports are the ones with `Custom` postfix

**Comment by andangrd** [comment]
you mean, I should write this code ?
```javascript
import { getNumberTypeCustom } from 'libphonenumber-js';
import metadata from '../../metadata.min.json';

export const getNumberType = (...args) => getNumberTypeCustom(...args, metadata); //error on this line

export const validate = errorKey => (value) => {
  if (isEmpty(value)) return undefined;

  const numberType = getNumberType(value, 'ID');
  console.log(numberType) //it return undefined
  if (numberType !== 'MOBILE') {
    return errorMessage;
  }
  return undefined;
};
```

it show an error. 
> TypeError: Cannot read property 'apply' of undefined

when i check index of the 'libphonenumber-js', it redirect to idex.common.js, and there is no custom function exported.
check this one : 
```javascript
'use strict'

var custom   = require('./custom')
var metadata = require('./metadata.min.json')

exports = module.exports = {}

exports.parse = function parse()
{
	var parameters = Array.prototype.slice.call(arguments)
	parameters.push(metadata)
	return custom.parse.apply(this, parameters)
}

exports.format = function format()
{
	var parameters = Array.prototype.slice.call(arguments)
	parameters.push(metadata)
	return custom.format.apply(this, parameters)
}

exports.get_number_type = function get_number_type()
{
	var parameters = Array.prototype.slice.call(arguments)
	parameters.push(metadata)
	return custom.getNumberType.apply(this, parameters)
}

exports.is_valid_number = function is_valid_number()
{
	var parameters = Array.prototype.slice.call(arguments)
	parameters.push(metadata)
	return custom.isValidNumber.apply(this, parameters)
}

exports.as_you_type = function as_you_type(country)
{
	custom.asYouType.call(this, country, metadata)
}

exports.as_you_type.prototype = Object.create(custom.asYouType.prototype, {})
exports.as_you_type.prototype.constructor = exports.as_you_type

exports.DIGIT_PLACEHOLDER = custom.DIGIT_PLACEHOLDER

// camelCase aliases
exports.getNumberType = exports.get_number_type
exports.isValidNumber = exports.is_valid_number
exports.asYouType = exports.as_you_type

```

**Comment by halt-hammerzeit** [comment]
You found a bug: `import { getNumberTypeCustom } from 'libphonenumber-js'` was missing from the ES6 export.
I added it in the newest release.
Try it and report back.

**Comment by halt-hammerzeit** [comment]
(alternatively one can use `import getNumberType from 'libphonenumber-js/custom` to reduce the resulting bundle size if the ES6 bundler can't handle proper tree shaking which can be the case currently)

**Comment by andangrd** [comment]
have you update the documentation?

**Comment by halt-hammerzeit** [comment]
Yes, I added a note on "tree-shaking" and the `/custom` export

**Comment by andangrd** [comment]
still get the same result, 
I have updated my package version, currently, I'm on this version:
> "libphonenumber-js": "^0.4.2",

could you please try this code in your environment?
example input number: 085867899998

```javascript
import { getNumberType as getNumberTypeCustom } from 'libphonenumber-js/custom';

export const getNumberType = (...args) => getNumberTypeCustom(...args, metadata);
export const phoneValidation = errorMessage => (number) => {
  if (isEmpty(number)) return undefined;

  const numberType = getNumberType(number, 'ID');
  console.log(numberType)  //return undefined
  if (!numberType) {
    return errorMessage;
  }
  return successMessage;
};
```

**Comment by halt-hammerzeit** [comment]
If you make up a sample project with simple reproduction instructions I could try that

**Comment by halt-hammerzeit** [comment]
Ok, I looked into this test case and turned out there was a minor bug in `getNumberType()` which is fixed in the newest version.

**Comment by andangrd** [comment]
I have tried the latest version, but it is still not passed my test cases,
I created new simple project to simulate this validation,
you can clone my repository here:

https://github.com/andangrd/simplePhoneValidation

I also create readme file, just follow the steps and please take a look at my code in src folder.

**Comment by halt-hammerzeit** [comment]
```
➜  simplePhoneValidation git:(master) npm run test

> simplePhoneValidation@0.0.1 test /Users/kuchumovn/work/simplePhoneValidation
> NODE_ENV=production jest --runInBand

 FAIL  src/phoneValidation.test.js
  ● Console

    console.log src/phoneValidation.js:8
      numberType for 085867899444 : MOBILE
    console.log src/phoneValidation.js:8
      numberType for +6285867899444 : MOBILE
    console.log src/phoneValidation.js:8
      numberType for 1234567890 : undefined
    console.log src/phoneValidation.js:8
      numberType for 0219533553 : MOBILE
```

So it's working.
I didn't use the `yarn` commands because I don't have it installed.
`npm install && npm test`

**Comment by andangrd** [comment]
>  FAIL  src/phoneValidation.test.js
it said failed.
last printed test case should be undefined or other than MOBILE, because it is a fixed line number / landline number

**Comment by halt-hammerzeit** [comment]
> numberType for 085867899444 : MOBILE

Which means it's working.

What exactly do you think isn't working.

**Comment by andangrd** [comment]
I mean this one:
>   console.log src/phoneValidation.js:8
      numberType for 0219533553 : MOBILE

when you open phoneValidation.js, you will see this test cases :
```javascript

describe('FormValidation', () => {
  test('phoneValidation', () => {
    expect(phoneValidation(ERROR_MESSAGE)('085867899444')).toBe(SUCCESS); //valid mobile phone number
    expect(phoneValidation(ERROR_MESSAGE)('+6285867899444')).toBe(SUCCESS); //valid mobile phone number
    expect(phoneValidation(ERROR_MESSAGE)('1234567890')).toBe(ERROR_MESSAGE); //invalid mobile phone number
    expect(phoneValidation(ERROR_MESSAGE)('0219533553')).toBe(ERROR_MESSAGE); //valid landline number but should be an invalid mobile phone number
    expect(phoneValidation(ERROR_MESSAGE)('+6221533553')).toBe(ERROR_MESSAGE); //valid landline number but should be aninvalid mobile phone number
    expect(phoneValidation(ERROR_MESSAGE)('+92421533553')).toBe(ERROR_MESSAGE); //invalid mobile phone number
    expect(phoneValidation(ERROR_MESSAGE)('4215335536')).toBe(ERROR_MESSAGE); //invalid mobile phone number
  });
});
```

**Comment by halt-hammerzeit** [comment]
So which exact phone numbers you think aren't working and what is the exact expected result

**Comment by halt-hammerzeit** [comment]
The one you said about is undetermined:
https://libphonenumber.appspot.com/phonenumberparser?number=0219533553&country=ID
`FIXED_LINE_OR_MOBILE`

**Comment by andangrd** [comment]
ah, ya..I think it will success and passed the test case when the value of getNumberType() is FIXED_LINE_OR_MOBILE.
but if you check your test result, it return "MOBILE" for this number 0219533553

>FAIL  src/phoneValidation.test.js
  ● Console

    console.log src/phoneValidation.js:8
      numberType for 085867899444 : MOBILE
    console.log src/phoneValidation.js:8
      numberType for +6285867899444 : MOBILE
    console.log src/phoneValidation.js:8
      numberType for 1234567890 : undefined
    console.log src/phoneValidation.js:8
      numberType for 0219533553 : MOBILE

so why we get different result? did I do wrong implementation your function? could you please take a look at my phoneValidation.js?

**Comment by halt-hammerzeit** [comment]
Yes, this turned out to be a small bug regarding `FIXED_LINE_OR_MOBILE` cases.
Fixed in the new release.

**Comment by andangrd** [comment]
cool, it works for the latest version.
thank you for your support @halt-hammerzeit 
👍

**Comment by mchtyener** [comment]
Hello, I am trying to validate Turkish (TR) mobile numbers using the libphonenumber-js library, but the phoneNumber.getType() function returns undefined for numbers parsed with parsePhoneNumber. For example, +905541785434 (a valid Turkish mobile number with the 554 operator prefix) is detected as undefined instead of MOBILE. Other tools on NPM or manual checks confirm that this number is indeed a mobile number.
Additionally, in some cases, the parsePhoneNumber call produces a ParseError: TOO_SHORT error, particularly for incomplete numbers (e.g., +905, +9055, etc.). This occurs frequently during real-time input validation (e.g., with ngx-mask), but unexpected behavior is also observed for complete numbers.
The issue likely stems from missing or incorrect metadata for Turkey. It appears that similar issues were discussed in issue #61, but I am still experiencing this problem in the current version.

**Comment by catamphetamine** [comment]
@mchtyener Hi,

> `phoneNumber.getType()` function returns `undefined` for numbers

See what type does the demo page show. If it shows `undefined` too then see the "Bug reporting" section of the readme. Most likely though there's no bug and nothing will be changed in the library.

> `parsePhoneNumber` call produces a ParseError: TOO_SHORT error, particularly for incomplete numbers (e.g., +905, +9055, etc.).

That's expected behavior. Use the default export that doesn't throw such an error.
